# -*- encoding : utf-8 -*-

deity = Deity.create(:name => "Brak/Ateizm")
deity = Deity.create(:name => "Magni", :description => "Magni jest bogiem prymitywnych mieszkańców gór. Wyznają go przede wszystkim barbarzyńcy, wojownicy jak i szamani. Najczęściej przedstawiany jest jako ponad dwumetrowy mężczyzna o potężnej budowie ciała. Głowa pokryta długimi rudymi włosami z długą tego samego koloru brodą, przypomina płonącą pochodnie. Skojarzenie to jest zdecydowanie na miejscu albowiem Magni znany jest ze swego porywczego jak ogień charakteru. W rękach trzyma potężny dwuręczny topór zwany „Katczr”. Zgodnie z wierzeniami za jego pomocą pokonał wielu spośród swych braci i sióstr, a krew każdego przeciwnika dodaje mu mocy. Postać jak i imponująca muskulatura potężnego boga okrywana jest często tylko przepaską biodrową. Nogi chronione są grubymi futrzanymi butami. Część legend i mitów opisujących boga gór przedstawia go również w postaci ogromnej, nieprzejednanej bestii. Podobno kiedy ogarnia go niekontrolowany szał, zmienia swe ciało i puszcza wodze krwawego zewu. Starcy niejednokrotnie opowiada o czystej potędze niszczącej na swojej drodze wszelaki opór. To sam bóg szuka krwi aby zaspokoić swój szał.
	Ulubionymi zwierzętami Magniego są mergi, wilki i niedźwiedzie, które doskonale odzwierciedlają jego naturę jak i dzikość serca.")
deity.countries << Country.where(name: ["Alantar", "Góry Księżycowe i Niczyje", "Wielkie Stepy", "Księstwa Wysp Północy", "Ziemie Sirtol"])
deity = Deity.create(:name => "Sirtol", :description => "Przeklęta, Matka Nienazwanych, Opiekunka Nieszczęścia, Sirtol – pierworodna Xargosa. Właściwie zawsze przedstawiana jest jako piękna, młoda kobieta. Kruczoczarne włosy, kaskadami spadające wokół łabędziej szyi, są doskonałym uzupełnieniem idealnej, boskiej twarzy. Najodważniejsi z trubadurów opowiadają jednak, że swe prawdziwe oblicze, ukazuje tylko w chwili kiedy zawładnie nią gniew i wściekłość. Zmienia się ona wtedy nie do poznania, i choć nadal jest zjawiskowa i kusząca wyzwolić potrafi strach i przerażenie nawet w najodważniejszych rycerzach Syriona. Posągi Sirtol właściwie zawsze dążą do idealnej formy, tak aby nie uchybić Mrocznej Pani, która nie zawsze jest pobłażliwa. Zwłaszcza kiedy artysta nie sprosta jej oczekiwaniom. Zwiewne szaty ukazują pełnie jej wdzięków, w wyniku czego co bardziej wstydliwi mogliby dostać niezdrowych wypieków spoglądając na rzeźby przedstawiające Matkę Demonów.
	Sirtol jest jedynym Bogiem żyjącym w świecie ludzi. Od czasu kiedy została wygnana i strącona przez swe rodzeństwo, tkwi na tym padole nie mogąc go opuścić. Oderwana od swojego świata i zamieszkujących go dzieci (demony) Sirtol cierpi w samotności. Pomimo przegranej sprzed wieków i potwornego upadku pierworodna nie pozostała dłużna swym braciom i siostrom. Ogarnięta szałem zemsty rzuciła na nich najpotężniejszą klątwę. I kiedy ostatnie słowa zostały wypowiedziane, żaden z nich nie mógł już odwiedzić świata śmiertelników. Zostali odcięci... a ich wpływ malał z czasem, aż właściwie całkowicie zaniknął.")
deity.countries << Country.where(name: ["Alantar", "Archipelag Południowy", "Księstwa Wysp Północy", "Ziemie Sirtol", "Złote Królestwa"])
deity = Deity.create(:name => "Smoczy Bóg", :description => "Przedwieczny przedstawiany jest w dwóch postaciach; pierwsza ukazuje go jako ogromnego, czarnego smoka, stojącego na dwóch tylnych łapach z rozpiętymi, błoniastymi skrzydłami. Największy i najwspanialszy pomnik znajduje się przed świątynią w stolicy Alantaru na Placu Dziękczynnym. Potężna, a zarazem niezwykła rzeźba wznosi się na ponad dwadzieścia metrów wysokości, jednakże nadal nie odzwierciedla jego ogromu. Nieliczni, którzy go widzieli, klną się na swe życie, że w prawdziwej postaci jest zdecydowanie większy. Aby przypomnieć ludziom Alantaru o ich marności i wątłości, pomnik został wzbogacony dodatkowymi elementami. To żywi, a raczej umierający ludzie, których przykuto łańcuchami do jego pazurów. Wrogowie wiary, państwa oraz inni pechowcy są teraz sobie równi, każdy umiera w cieniu Przedwiecznego. Ponadto postać czarnego smoka jest głównym elementem pancerzy, ryngrafów, sztandarów i mundurów całego Alantaru.
	Drugie oblicze utrwalane przez wieki w umyśle każdego obywatela cesarstwa to jego spersonifikowana postać mężczyzny. Przeraźliwie chudy starzec ma srebrzyste, długie włosy opadające na plecy. Wysuszona skóra powleka jego ciało niczym niezniszczalna szata, ukazując każdy mięsień i każde ścięgno. Po obu stronach szczęki, widnieją równo przystrzyżone bokobrody. Starzec  zawsze ukazywany jest na tronie lub w jego ścisłym pobliżu. Ubrany w powłóczyste szaty trzyma na swych kościstych kolanach ciężki obusieczny miecz. I choć powinno by się wydawać, że jest zmęczony, osoby widzące jego podobiznę przepełnione są jedynie zalążkami respektu przemieszanego ze strachem. Jednak to nie postura Smoka, ani jego ciało zapadają w pamięć. Najgorszy jest wzrok Przedwiecznego, w pewien sposób pusty, bez wyrazu, a zarazem pozbawiony ludzkich atrybutów. I kiedy dobrze się nad tym zastanowić, człowiek zdaje sobie sprawę z wszystkich rzeczy, które Obrońca widział i doświadczył. Wieki okropności, wojen, zdrady i nienawiści. Wieki obcowania z ludzką rasą. Wieki samotności przepełnionej świadomością i pamięcią o wyniszczonej rasie, o swych braciach i siostrach zdradzonych przez bogów.
	Samotna egzystencja musiała zniszczyć jego szlachetność i wiarę. Oddarła go z nadziei pozostawiając jedynie chęć zemsty. Na szczęście Przedwieczny jest nieskończenie cierpliwy, krok po kroku realizuje swoje plany, wiążąc z wybranym ludem ogromne nadzieje. Nadzieje, które stworzył ofiarując ludziom swego potomka, zrodzonego ze związku Smoka z kobietą. Wybrańca, który stanie się władcą świata. Tak nieśmiertelny cesarz, syn ostatniego Smoka stał się przywódcą małego księstewka i po kilkudziesięciu latach przeobraził je w największą potęgę lądową znanego świata.
	Wiara w Przedwiecznego jak i wszystkie dogmaty tworzące prawa Alantaru powiązane są ze sobą głosząc wszem i wobec o boskości cesarza. Tak więc religia ta jest deistyczna, jednak większość oczu i modlitw skupia się wokół osoby władcy.")
deity.countries << Country.where(name: ["Alantar", "Nimer", "Pelmir", "Wielkie Stepy", "Księstwa Wysp Północy", "Ziemie Sirtol"])
deity = Deity.create(:name => "Syrion", :description => "Syrion przedstawiany jest jako potężny mężczyzna w sile wieku o szlachetnych rysach twarzy. Najczęściej ubrany jest w piękny, złoty napierśnik trzymając nadziak lub inną broń obuchową oraz tarcze z wyrzeźbionym słońcem. Patron Pelmiru jest bogiem o czystym sercu, odważnym i honorowym. Wyznawcy często nazywają go Walecznym i nie jest to tylko czczy tytuł. Syrion jest opiekunem porządku i sprawiedliwości. Ponadto darzy sympatią wszystkich tych, którzy są honorowi, odważni i prawi.")
deity.countries << Country.where(name: ["Alantar", "Nimer", "Pelmir"])
deity = Deity.create(:name => "Durgil", :description => "przedstawiany jest jako starzec o dobrodusznej, łagodnej twarzy. Są to jednak tylko pozory. W rzeczywistości władca Nimeru jest bogiem wielbiącym porządek i sprawiedliwość. W swoich praw, sądach i decyzjach jest stanowczy żeby nie powiedzieć bezlitosny. Dlatego każdy człowiek, który stanie na jego drodze lub złamie prawo musi liczyć się z surową karą.
	Zgodnie z nimeryjskimi wierzeniami Durgil zasiada na ogromnym, kamiennym tronie w  swej wiecznej siedzibie. Majestatyczny pałac Kalorgard, znajduje się na szczycie najwyższej góry Nimeru, która zawsze pokryta jest lodem i śniegiem – Awarharze. Stąd, wszystko widzącym wzrokiem, obserwuje i ocenia swoich wiernych poddanych.")
deity.countries << Country.where(name: ["Nimer", "Pelmir"])
deity = Deity.create(:name => "Alaj", :description => "Bóg biednych i nieszczęśliwych przedstawiany jest jako młody, przystojny mężczyzna o nad wyraz spokojnej i przyjaznej twarzy. Ubrany jest w białe szaty kapłańskie, a w ręku dzierży piękną rzeźbioną laskę. Ponieważ Alaj nie pożądał niczego poza pokojem i dobrobytem dla wszystkich, nigdy nie otrzymał swoich ziem. Tak też żadne państwo nie jest jego, jednak cześć oddawana jest mu wszędzie. Koniec końców świat wypełniony jest po brzegi biednymi, zapomnianymi i skrzywdzonymi ludźmi. Dlatego Alaj obecny jest w każdym kraju i gości w większości ludzkich serc. W związku z bliską przyjaźnią z Syrionem oficjalny kult jak i świątynie najczęściej występują na terenie Pelmiru.")
deity.countries << Country.where(name: ["Alantar", "Nimer", "Pelmir", "Złote Królestwa"])
deity = Deity.create(:name => "Fortuna", :description => "Fortuna jest zapomnianą boginią, wieki temu była jednym z najważniejszych bóstw całego panteonu. Jednak czasy się zmieniły, żadne terytorium ani państwo nie jest  nią związane. Niewielu oddaje jej regularny hołd czy cześć, a w obecnych czasach rzadko kiedy można znaleźć chociażby próbę opisania jej wyglądu. W kilku miejscach na świecie można jeszcze odnaleźć samotnie stojący pomnik lub małą świątynie przypominającą o potędze, która została zapomniana. Jak widać władczyni losu nie przewidziała swojego upadku ani nie mogła zmienić porażki w sukces. To smutne i tragiczne, tak samo jak losy tysięcy ludzi na świecie. Jednak kto wie, może szczęście znowu się do niej uśmiechnie, może znów ludzie zaczną się do niej modlić i przypomną sobie minione czasy świetności...")
deity.countries << Country.where(name: ["Alantar", "Archipelag Południowy", "Góry Księżycowe i Niczyje", "Nimer", "Pelmir", "Wielkie Stepy", "Księstwa Wysp Północy", "Ziemie Sirtol", "Złote Królestwa"])
deity = Deity.create(:name => "Kalastra", :description => "pierwsza z bogiń po Xargosie została stworzona doskonałą. Idealne kształty i oblicze miały cieszyć boga ojca po kraniec świata. Czas jednak okazał się dla niej okrutny, wydarzenia z wojny bogów, utrata męża oraz wielu dzieci, odcisnęły na niej straszliwe piętno. Od kiedy ślad po niej zaginął, nie dawała znaku życia przez kilkanaście wieków, teraz jednak daje się słyszeć pogłoski o jej powrocie.")
deity.countries << Country.where(name: ["Archipelag Południowy"])
deity = Deity.create(:name => "Galos i Malos", :description => "mieszkańcy Północnych Wysp modlą się do dwóch bliźniaków - Galosa i Malosa. Pierwszy z nich uważany jest za dobre wcielenie natury, sprowadza ryby, pomaga żeglarzom. Przedstawiany jest często pod postacią mewy, a same ptaki zwiastują szczęśliwy powrót do domu i spokojną pogodę (uważane są za święte zwierzęta). Żeglarze modlą się do niego o szczęśliwy powrót z mórz i oceanów. Ponadto odpływ kojarzony jest z łagodniejszym z bliźniaków. Uzasadnione jest to zjawiskiem pozostawiania przez morze cennych skarbów. Szczęśliwcy, którzy poszukują takich zdobyczy czasami odnajdują niezwykłe znaleziska. Natomiast Malos odpowiedzialny jest za przypływ i jego niszczycielską moc, dlatego ludzie składają dary przed jego nadejściem aby zaspokoić głód i gniew straszliwego boga. Drugi bliźniak odpowiedzialny jest również za sztormy (gniew mórz i oceanów) oraz za powodzenie podczas bitwy. Malos jest patronem pojedynków, sądów oraz wojowników. To jego imię wypowiadane jest przed i podczas walki.")
deity.countries << Country.where(name: ["Alantar", "Księstwa Wysp Północy", "Ziemie Sirtol", "Złote Królestwa"])
deity = Deity.create(:name => "Calisto", :description => "Calisto bogini wszystkich czterech żywiołów, jest opiekunką i strażniczką przyrody. Przedstawiana jest jako kobieta w średnim wieku o spokojnym obliczu, ubrana w szaty z roślin, z pięknymi, długi, rozwianymi włosami. Ponadto wizerunek Calisto zależny jest od części świata z jakiej pochodzi. Dlatego jej strój czasem przypominać może roślinność morską, a kiedy indziej zbliżony będzie do wizerunku flory kontynentalnej. Tak na dobrą sprawę, wygląd bogini w każdym państwie jest odmienny, jednak łączy go wspólny motyw związany z przyrodą.")
deity.countries << Country.where(name: ["Alantar", "Archipelag Południowy", "Góry Księżycowe i Niczyje", "Nimer", "Pelmir", "Wielkie Stepy", "Ziemie Sirtol", "Złote Królestwa"])
deity = Deity.create(:name => "Kal-Kalar")
deity.countries << Country.where(name: ["Alantar", "Góry Księżycowe i Niczyje", "Wielkie Stepy", "Księstwa Wysp Północy", "Ziemie Sirtol", "Złote Królestwa"])
deity = Deity.create(:name => "Kastor", :description => "bóg złodziei, oszustów, zdrady i hazardu jest ostatnim z dzieci Kalastry i Xargosa. Ludzie mówią, iż już od momentu urodzić był ułomny, a okres dorastania tylko pogorszył jego charakter. Słaby, chorowity i pozostawiony samemu sobie, cierpiał nieludzkie katusze. Czy jest to jednak wystarczająca wymówka dla wszystkich strasznych rzeczy, których dokonał? Kastor przedstawiany jest jako dorosły mężczyzna, szczupły o lisiej twarzy, kojarzony jest z wszystkimi negatywnymi cechami jakie mogą drzemać w śmiertelnikach. Po wydarzeniach, które zmieniły losy świata, uciekł i nikt nie potrafi go odnaleźć. Jednak nadal przemawia do swych wybrańców, knując i spiskując przeciw starszemu rodzeństwu. ")
deity.countries << Country.where(name: ["Archipelag Południowy"])
deity = Deity.create(:name => "Samotnik", :description => "Zwany też Władcą Smutku jest jedynym bogiem, który nie chciał być władcą ludzi. Kiedy inni dzielili ziemie i wpływy on odszedł na jedyne pustkowia, które nikogo nie interesowały. Przytłoczony śmiercią rodzeństwa, wypędzeniem ojca i upadkiem Sirtol, wybrał samotność i spokój. Kiedy zniknął, wielu próbowało go odnaleźć, jednak mróz i ciemności zapewniły mu bezpieczny azyl. Spokój ogarnął jego ciało i umysł, powoli z dnia na dzień, z miesiąca na miesiąc odnalazł ostateczną niczym nie zmąconą ciszę. Stan, który mógł ocalić jego ojca od szaleństwa, jednak Xargos nigdy o tym nawet nie pomyślał. Bóg ojciec był inny, chciał działać, mieć wpływ na wszystko i wszystkich. I co mu z tego przyszło? Jego syn wiedział jednak, że natłok wydarzeń, chaos, wojny i gniew, mogą zniszczyć nawet najdoskonalszych. Jeżeli minione wydarzenia zrujnowały jego matkę i ojca, świat odciśnie na nim swoje piętno i nie będzie dla niego łaskawszy. To smutne i pożałowania godne, lecz niektórych rzeczy nie można zmienić. Inni mogą próbować, będą się szarpać, zmagać, biadolić, a koniec i tak będzie tragiczny, powtarzalny i nie trzeba żadnego wróżbity aby go odgadnąć. Samotnik opatulił się szorstkim, grubym płaszczem. Po raz kolejny spojrzał na kojący bezmiar lodowca. Gdzieniegdzie pojawiały się małe strumyki, powoli nadchodziła odwilż. Który to już raz? Setny, tysięczny … kto wie, przecież czas nie gra szczególnej roli. Roztarł skostniałe dłonie i skierował się ku północy. Kolejna podróż, znowu odnajdzie ciszę i chłód, który tak lubi. Przeczeka szalone czasy zmian i niepożądanych gości, uśmiechnął się szeroko do siebie. Spokój, cel, który musi utrzymać ponad wszystko, właściwie jak się nad tym zastanowić jest to jedyna sprawa, która jeszcze się liczy. Musi być sam, całkowicie sam.
	Samotnik nie posiada żadnego oficjalnego kultu ani ustabilizowanej religii czy chociażby świątyń. Pojedyncze osoby, których jest naprawdę niewiele, zwracają się do niego w modłach, jednakże nie mają żadnych złudzeń. Zdają sobie doskonale sprawę z obojętności Boga. Ponadto czasami ludzie, którzy utożsamiają się z nim lub jego poglądami zapalą świeczkę pozdrawiając go i jego lodową krainę.
	Władca Smutku jest jedynym bogiem, którego nie dosięgnęła klątwa Sirtol. ")

deity = Deity.create(:name => "Xargos")
deity.countries << Country.where(name: ["Archipelag Południowy"])














