['Schizofrenik', 'bohater prześladowany jest przez swoje drugie \'Ja\' czasem lepsze, czasem gorsze, jednakże zawsze inne. Klątwa ta daje tak ogromne spektrum możliwości, iż po odpowiedniej dyskusji i analizie wraz z MG, gracz może właściwie dowolnie ukształtować swoją osobowość. Zmiany charakteru jak i częstotliwość pojawiania się drugiej połowy zależą głównie od MG i wstępnych ustaleń.'],
['Megaloman', 'postać przepełniona jest pewnością o swojej doskonałości. Wie, że jest wcieleniem perfekcji, może jakimś zapomnianym Bogiem bądź wypędzonym królem – pozbawiony wad i przywar chodzący ideał. Chce o wszystkim decydować, zawsze zabiera głos, dąży do przewodzenia, musi być pierwsza, najlepsza i najlepiej jedyna w swoim rodzaju. Oczywiście nie przyjmuje słów krytyki, zwalając winę i odpowiedzialność na osoby trzecie bądź wyjątkowo pechowe okoliczności, których nikt nie mógł przewidzieć ani im zapobiec. Osoba taka w zależności od sytuacji i nastawienia osób trzecich ma chwilowo zwiększoną lub zmniejszoną Ogładę o 5pkt. (decyzja MG).'],
['Grubas', 'postać jest niesłychanie gruba, zwały tłuszczu niczym obwarzanki otaczają większość jej kończyn tworząc wyjątkowo urokliwy widok. Bohater otrzymuje -2pkt do \'Ogłady\' oraz -4pkt do \'Zręczności\'. Ponadto musi dwukrotnie więcej jeść niż przeciętny człowiek a jej ubrania i zbroje są zdecydowanie droższe od przeciętnych egzemplarzy – zazwyczaj wykonuje je na specjalne zamówienie.'],
['Słabeusz', 'postać jest chorowicie słaba, jej organizm ciągle wydaje się być zmęczony niczym po ogromnym wysiłku. Po wyliczeniu parametru \'Siła\' dzielimy go na pół zaokrąglając w górę. Wartość tego współczynnika nigdy nie będzie mogła przekroczyć 20pkt.'],
['Amnezja', 'postać obdarzona jest wyjątkowo słabą pamięcią (albo miała przykry wypadek, który spowodował utratę wspomnień wraz z częścią wiedzy). Dlatego też po wybraniu postaci i wyliczeniu wolnych umiejętności wynikających z Inteligencji oraz klasy dzielimy uzyskaną wartość na pół zaokrąglając w dół.'],
['Chromy (kulawy)', 'postać nie może korzystać z zasady sprintu (jego sprint równy jest biegowi) ponadto otrzymuje karę do Zręczności -3pkt; a parametr ten nigdy będzie mógł przekroczyć 20pkt.'],
['Epilepsja', 'postać cierpi na nagłe ataki epilepsji, które mają miejsce w najróżniejszych momentach. Aby sprawdzić czy gracz będzie miał pecha należy na początku każdego dnia wykonać rzut k30 wylosowanie wartości 1-2 oznacza iż biedak dzisiejszego dnia będzie miał niekontrolowany napad. Następnie MG wykonuje kolejny sekretny rzut k30 jeżeli po raz kolejny wypadnie jedynka lub dwójka postać miała prawdziwego pecha i przydarzy się to w najgorszym możliwym miejscu i czasie. Oczywiście gdzie, jak i kiedy zależy do decyzji MG.'],
['Ryzykant', 'postać ma niesamowitą ciągotę do ryzyka, niebezpieczeństwa i ogromnych dawek adrenaliny. Najczęściej objawia się to poprzez częste pojedynki, bijatyki, szaleńcze przygody i wyzwania. Co gorsza bohater całkowicie pozbawiony jest racjonalnej oceny sytuacji i rozmijając się z prawdą brnie w coraz to większe problemy (często wciągając w to drużynę i swoich przyjaciół). Wykonując testy strachu postać zawsze otrzymuje automatyczny sukces (chyba, że MG ma podstawy do tego aby wykonać normalny test – zazwyczaj związane jest to z działaniem czarów kiedy to udany test i tak oznacza pewne minusy dla ofiary zaklęcia).'],
['Garbaty', 'postać urodziła się z garbem, jej Zręczność i Ogłada zmniejszone są o k10pkt. Parametry te nigdy nie mogą przekroczyć 20pkt a bohater często staje się obiektem drwin i niesmacznych żartów.'],
['Tchórz', 'postać jest tchórzliwa, często salwuje się ucieczką, woli nie podejmować zbędnego ryzyka, chociaż często zdarza jej się przechwalać i opowiadać o swoich wyczynach. Po wyliczeniu parametru „Wiara” dzielimy go na pół zaokrąglając w górę. Wartość tego współczynnika nigdy nie może przekroczyć 15pkt.'],
['Niezdara', 'postać jest wyjątkowo niezgrabna, często się potyka, przewraca, wpada na innych, itp. Po wyliczeniu parametru „Zręczność” dzielimy go na pół zaokrąglając w górę. Wartość tego współczynnika nigdy nie może przekroczyć 15pkt.'],
['Karzeł', 'postać otrzymuje -2pkt do Zręczności, Siły i Ogłady a ponadto parametry te nigdy nie będą mogły przekroczyć 20pkt. (wyjątek stanowi premia z magii). Wzrost postaci równy jest 150cm minus 2k10pkt. Klątwa ta najrzadziej występuje wśród barbarzyńców z Gór. Jednakże dzieci rodzące się tam, obarczone tym przekleństwem najczęściej traktowane są niczym trędowaci, dlatego ich los jest zazwyczaj przypieczętowany. Muszą opuścić wioskę/klan i od tej pory radzić sobie same – oczywiście można powiedzieć, że jest to równoznaczne z wyrokiem śmierci, chociaż nielicznym udaje się dotrzeć do cywilizacji bądź napotkać kupców zmierzających górskimi szlakami, którzy mogą takie biedactwo uratować. Wśród barbarzyńców krąży legenda o karle, który został poczęty przez Magniego podczas kazirodczego aktu z własną matką Kalastrą; boginią szaleństwa. Dziecko urodziło się nie tylko z ułomnym ciałem ale co gorsza odziedziczyło opętany umysł swej matki, ogarnięte nienawiścią, zgorzkniałe, odrzucone przez oboje rodziców pełza po świecie mszcząc się na niewinnych i słabych.'],
#Klątwa wieku – codziennie rano o świcie MG wykonuje rzut k10 jeżeli wypadnie 1-2 nieszczęśnik zamienia się w zniedołężniałego starca. Parametry główne i PŻ zmniejszane są do połowy (zaokrąglając w górę) a moc klątwy utrzymuje się, aż do następnego Świtu, kiedy to bohater odzyskuje normalny wiek.
#Niewola krwi – raz na k10 dni postać musi wypić świeżą, ludzką krew (około 1litra). MG sekretnie wykonuje rzut po czym w dniu żądzy krwi informuje gracza o narastającym pragnieniu. Za każdy dzień, w którym postać nie wypije krwi otrzymuje -2pkt do parametrów głównych. Dzieje się tak, aż do chwili kiedy współczynniki zredukowane zostaną do 5pkt co oznacza stan maligny i odruchy wręcz zwierzęce.
#Pomiot/Robactwo – postać prześladowana jest przez wszelkiego rodzaju insekty; pchły, wszy, kleszcze, komary, pająki, itp. stworzenia. Nie sposób jest się ich pozbyć po prostu w ciągu nocy nowe zastępy znowu odnajdą nieszczęśnika. „Ogłada” postaci spada do połowy (za wyjątkiem przemówień gdzie czasami można zastosować jej podstawową wartość, np.: nie jest widoczna, itp.).
#Zgnilizna – na postaci ciąży straszna klątwa, jej ciało ulega ciągłemu gniciu, rozpadowi. Jednakże w przeciwieństwie do trądu nigdy nie spowoduje to jej śmierci (ani utraty części ciała). Postać zmniejsza swoją Ogładę o -10pkt do minimum do 5pkt i PŻ o -5pkt. Towarzyszy jej ciągły smród, napady bólu, ropienie, itp. Oprócz tego rany postaci nie chcą się goić, dlatego na leczenie musi poświęcić dwukrotnie więcej czasu i pieniędzy.
#Albinos – postać dotknięta jest bielactwem (brakiem barwnika), przez większość ludzi postrzegana jest jako odmieniec. Jej Ogłada zmniejszona jest o 5pkt. Wyjątek stanowi Nimer gdzie Albinos uważany jest za wybrańca bożego tego, na którego padł wzrok Durgila i jego nieopisana mądrość (włosy białe/siwe są oznaką mądrości). Dlatego w tym kraju prezencja Albinosa zamiast ulec redukcji jest podnoszona o 5pkt; (Ogłada postaci powinna zostać zapisana jako podstawowa wartość oraz ta zwiększona, której używamy na czas pobytu w Nimerze). Niektórzy, zacofani i głupi ludzie (zazwyczaj chłopi) mogą bać się Albinosa, dlatego MG może dodać +5pkt do Ogłady podczas testów zastraszania.
#Głupek – postać straciła rozum, jest naiwna, prosta, tępa… Jej Inteligencja jest połowiona. Chociaż na pierwszy rzut oka granie taką postacią wydaje się bezsensowne należy pamiętać, iż zabawa w RPG polega głównie na odgrywaniu roli – tych łatwiejszych i tych trudniejszych. Przecież każdy z nas potrafi zagrać potężnego, nieustraszonego wojownika, a czy każdy podoła wyzwaniu zagrania głupka? Posiadając tą klątwę należy pamiętać, że ludzi głupich jest tak samo wielu jak tych mądrych warto się zastanowić nad taka postacią albowiem może ona być łatwowierna, może być fanatykiem religijnym, itd., możliwości jest naprawdę sporo wystarczy tylko trochę się zastanowić.
#
#
#    [].each do |trait|
#
#    end